version: '2.0'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: elasticsearch
    environment:
      - cluster.name=weather-cluster
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - esdata1:/usr/share/elasticsearch/data

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: elasticsearch2
    environment:
      - cluster.name=weather-cluster
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    volumes:
      - esdata2:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    ports:
     - "5601:5601"
    links:
     - "elasticsearch2:elasticsearch"

  metar-weather:
    build: ./
    environment:
      - "ES_URL=elasticsearch:9200"
    volumes:
      - metardata:/metar
    links:
     - "elasticsearch:elasticsearch"

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  metardata:
    driver: local