version: '3.0'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: elasticsearch
    environment:
      - cluster.name=weather-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: elasticsearch2
    environment:
      - cluster.name=weather-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    ports:
     - "5601:5601"
    links:
     - "elasticsearch:elasticsearch"
    networks:
      - esnet

  metar-weather:
    build: ./
    environment:
      - "ES_URL=elasticsearch:9200"
    volumes:
      - metardata:/metar
    links:
     - "elasticsearch:elasticsearch"
    networks:
     - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  metardata:
    driver: local

networks:
  esnet:
