version: '3.8'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-cluster
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - discovery.seed_hosts=elasticsearch, elasticsearch2
      - cluster.initial_master_nodes=elasticsearch, elasticsearch2
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - opensearch-net

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    container_name: elasticsearch2
    environment:
      - node.name=elasticsearch2
      - cluster.name=es-cluster
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch, elasticsearch2
    depends_on:
      - elasticsearch
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - opensearch-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.6
    ports:
     - "5601:5601"
    links:
     - "elasticsearch"
    networks:
      - opensearch-net

  metar-weather:
    build: .
    volumes:
      - ./metar:/metar
    ports:
      - "8080:8080"
    environment:
      - ENV_VAR=example
      - "ES_URL=http://elasticsearch:9200"
    depends_on:
      - elasticsearch
    networks:
      - opensearch-net

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  metardata:
    driver: local

networks:
  opensearch-net:
